name: Dev Build without Nix
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/rust
        asset_name: rustom-mastodon-bot_x86-64
        prerelease: true
        overwrite: true
        tag: dev
        release_name: dev release