name: Dev Build on arm
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu_latest

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          cargo build --release
          cp target/release/rust /artifacts/rust
    - name: Build
      run: cargo build --release
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${PWD}/artifacts/rust
        asset_name: rustom-mastodon-bot_arm64
        prerelease: true
        overwrite: true
        tag: dev
        release_name: dev release